begin;

create extension if not exists pgtap with schema extensions;
select plan(20);

insert into auth.users (
  id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  created_at, updated_at, raw_app_meta_data, raw_user_meta_data
)
values
  ('44000000-0000-4000-8000-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'transfer.origin@test.local', '', now(), now(), now(), '{}', '{"full_name":"Empleado Origen"}'),
  ('44000000-0000-4000-8000-000000000002', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'transfer.destination@test.local', '', now(), now(), now(), '{}', '{"full_name":"Empleado Destino"}');

insert into public.work_shifts (id, location_id)
values
  ('54000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001'),
  ('54000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000002');

insert into public.openings (work_shift_id, created_by, cash_opening)
values
  ('54000000-0000-4000-8000-000000000001', '44000000-0000-4000-8000-000000000001', 0),
  ('54000000-0000-4000-8000-000000000002', '44000000-0000-4000-8000-000000000002', 0);

select ok(not has_table_privilege('authenticated', 'public.transfers', 'INSERT'), 'direct transfer inserts are revoked');
select ok(not has_table_privilege('authenticated', 'public.transfers', 'UPDATE'), 'direct transfer updates are revoked');
select ok(not has_table_privilege('authenticated', 'public.transfer_items', 'INSERT'), 'direct item inserts are revoked');
select ok(not has_table_privilege('authenticated', 'public.transfer_items', 'UPDATE'), 'direct item updates are revoked');

set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"44000000-0000-4000-8000-000000000001","role":"authenticated"}', true);

select lives_ok(
  $$select public.send_transfer(
    '54000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000002',
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":10},{"product_id":"20000000-0000-4000-8000-000000000004","quantity":2.5}]'::jsonb
  )$$,
  'origin employee atomically creates and sends a transfer'
);

select results_eq(
  $$select count(*)::bigint from public.transfers
    where status = 'SENT'
      and sent_by = '44000000-0000-4000-8000-000000000001'
      and sent_at is not null$$,
  'values (1::bigint)',
  'sent metadata is generated by the server'
);
select results_eq('select count(*)::bigint from public.transfer_items', 'values (2::bigint)', 'all sent items are stored');

select throws_ok(
  $$select public.send_transfer(
    '54000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000001',
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":1}]'::jsonb
  )$$,
  'P0001', 'TRANSFER_SAME_LOCATION', 'origin and destination must differ'
);
select throws_ok(
  $$select public.send_transfer(
    '54000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000002',
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":1.5}]'::jsonb
  )$$,
  'P0001', 'TRANSFER_UNIT_QUANTITY_REQUIRED', 'UNIT sent quantities must be whole numbers'
);
select results_eq('select count(*)::bigint from public.transfers', 'values (1::bigint)', 'failed sends leave no partial transfer');

reset role;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"44000000-0000-4000-8000-000000000002","role":"authenticated"}', true);

select throws_ok(
  $$select public.receive_transfer(
    (select id from public.transfers limit 1),
    '54000000-0000-4000-8000-000000000002', null,
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":9},{"product_id":"20000000-0000-4000-8000-000000000004","quantity":2.5}]'::jsonb
  )$$,
  'P0001', 'TRANSFER_DIFFERENCE_NOTES_REQUIRED', 'quantity differences require notes'
);
select results_eq(
  'select count(*)::bigint from public.transfer_items where received_quantity is not null',
  'values (0::bigint)',
  'rejected receipt leaves item quantities unchanged'
);

select lives_ok(
  $$select public.receive_transfer(
    (select id from public.transfers limit 1),
    '54000000-0000-4000-8000-000000000002', 'Faltó una empanada en el paquete',
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":9},{"product_id":"20000000-0000-4000-8000-000000000004","quantity":2.5}]'::jsonb
  )$$,
  'destination employee confirms actual quantities'
);
select results_eq(
  $$select count(*)::bigint from public.transfers
    where status = 'RECEIVED_WITH_DIFFERENCES'
      and received_by = '44000000-0000-4000-8000-000000000002'
      and reception_notes = 'Faltó una empanada en el paquete'$$,
  'values (1::bigint)',
  'difference status and notes remain auditable'
);
select results_eq(
  $$select received_quantity::numeric from public.transfer_items
    where product_id = '20000000-0000-4000-8000-000000000001'$$,
  'values (9::numeric)',
  'destination stores actual received quantity'
);
select throws_ok(
  $$select public.receive_transfer(
    (select id from public.transfers limit 1),
    '54000000-0000-4000-8000-000000000002', null,
    '[{"product_id":"20000000-0000-4000-8000-000000000001","quantity":9},{"product_id":"20000000-0000-4000-8000-000000000004","quantity":2.5}]'::jsonb
  )$$,
  'P0001', 'TRANSFER_NOT_RECEIVABLE', 'a transfer cannot be received twice'
);

reset role;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"44000000-0000-4000-8000-000000000001","role":"authenticated"}', true);
select lives_ok(
  $$select public.send_transfer(
    '54000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000002',
    '[{"product_id":"20000000-0000-4000-8000-000000000002","quantity":4}]'::jsonb
  )$$,
  'a second transfer can be sent'
);

reset role;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"44000000-0000-4000-8000-000000000002","role":"authenticated"}', true);
select lives_ok(
  $$select public.receive_transfer(
    (select id from public.transfers where status = 'SENT' limit 1),
    '54000000-0000-4000-8000-000000000002', 'This note is discarded when quantities match',
    '[{"product_id":"20000000-0000-4000-8000-000000000002","quantity":4}]'::jsonb
  )$$,
  'matching receipt completes normally'
);
select results_eq(
  $$select count(*)::bigint from public.transfers
    where status = 'RECEIVED' and reception_notes is null$$,
  'values (1::bigint)',
  'matching receipt uses RECEIVED without discrepancy notes'
);
select results_eq(
  $$select count(*)::bigint from public.transfers
    where destination_work_shift_id = '54000000-0000-4000-8000-000000000002'$$,
  'values (2::bigint)',
  'both receipts are assigned to the open destination shift'
);

select * from finish();
rollback;
